apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.operatorNamespace }}
  labels:
    {{- include "kuberay-odh-operator.labels" . | nindent 4 }}
