apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ray.io_rayclusters.yaml
  - ray.io_rayjobs.yaml
  - ray.io_rayservices.yaml
  - scc.yaml
  - webhook-service.yaml
  - webhook-config.yaml
