//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *Ray) DeepCopyInto(out *Ray) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Ray) DeepCopy() *Ray {
	if in == nil {
		return nil
	}
	out := new(Ray)
	in.DeepCopyInto(out)
	return out
}

func (in *Ray) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RayList) DeepCopyInto(out *RayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ray, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RayList) DeepCopy() *RayList {
	if in == nil {
		return nil
	}
	out := new(RayList)
	in.DeepCopyInto(out)
	return out
}

func (in *RayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RaySpec) DeepCopyInto(out *RaySpec) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
}

func (in *RaySpec) DeepCopy() *RaySpec {
	if in == nil {
		return nil
	}
	out := new(RaySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RayStatus) DeepCopyInto(out *RayStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

func (in *RayStatus) DeepCopy() *RayStatus {
	if in == nil {
		return nil
	}
	out := new(RayStatus)
	in.DeepCopyInto(out)
	return out
}
