---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kuberay-mutating-webhook-configuration
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: kuberay-webhook-service
        namespace: opendatahub
        path: /mutate-ray-io-v1-raycluster
    failurePolicy: Fail
    name: mraycluster.kb.io
    rules:
      - apiGroups:
          - ray.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - rayclusters
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kuberay-validating-webhook-configuration
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: kuberay-webhook-service
        namespace: opendatahub
        path: /validate-ray-io-v1-raycluster
    failurePolicy: Fail
    name: vraycluster.kb.io
    rules:
      - apiGroups:
          - ray.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - rayclusters
    sideEffects: None
